### ISSUE TITLE
key pressed propagating to text field on next screen

### ISSUE THREAD

**Issue by workboxsoftware** [jacobbuck/react-use-keypress#5]
On a listing screen, if user presses the "n" key for new transaction I switch routes to show a data entry screen.  The first field on the screen is set to autofocus.  But the "n" typed on the previous screen shows up in the first text field.  Is there a way to stop that from happening?

Nice utility - thank you!

**Comment by aliebuck** [comment]
Sounds like you need to call the [`preventDefault`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) method on the `event` argument in the hook—this will prevent the browsers native behaviour. For example:

```js
   useKeypress('n', (event) => {
     event.preventDefault();
     // your logic here
   })
```
