### ISSUE TITLE
Add Typescript definition

### ISSUE THREAD

**Issue by ValentinH** [jacobbuck/react-use-keypress#6]
Are you interested in a PR that would be adding a `index.d.ts` to provide typings for this library?

I think it should be something like this:
```ts
declare module 'react-use-keypress' {
  export default function useKeyPress(
    key: KeyboardEvent['key'] | KeyboardEvent['key'][],
    callback?: (e: KeyboardEvent) => void
  );
}

```

**Comment by aliebuck** [comment]
Hey thanks for this. Currently I'm not using TypeScript so I'd prefer not to maintain typings. Feel to contribute this to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead.

**Comment by ValentinH** [comment]
Alright 😔
